CREATE TABLE [dbo].[AspNetUsers] (
    [Id]                   NVARCHAR (128) NOT NULL,
    [CoachingType]         NVARCHAR (256) NULL,
    [Description]          NVARCHAR (1000) NULL,
    [WorkLocation]         NVARCHAR (25) NULL,
    [Qualification]        NVARCHAR (256) NULL,
    [Specialization]       NVARCHAR (50) NULL,
    [Email]                NVARCHAR (256) NULL,
    [EmailConfirmed]       BIT            NOT NULL,
    [PasswordHash]         NVARCHAR (MAX) NULL,
    [SecurityStamp]        NVARCHAR (MAX) NULL,
    [PhoneNumber]          NVARCHAR (MAX) NULL,
    [PhoneNumberConfirmed] BIT            NOT NULL,
    [TwoFactorEnabled]     BIT            NOT NULL,
    [LockoutEndDateUtc]    DATETIME       NULL,
    [LockoutEnabled]       BIT            NOT NULL,
    [AccessFailedCount]    INT            NOT NULL,
    [UserName]             NVARCHAR (256) NOT NULL,
    [Discriminator]        NVARCHAR (128) DEFAULT ('') NOT NULL,
    [FirstName]            NVARCHAR (MAX) NULL,
    [LastName]             NVARCHAR (MAX) NULL,
    [DOB]                  DATETIME       DEFAULT ('1900-01-01T00:00:00.000') NOT NULL,
    [Height]               FLOAT (53)     NULL,
    [Weight]               FLOAT (53)     NULL,
    [TargetWeight]         FLOAT (53)     NULL,
    [TargetDate]           DATETIME       NULL,
    [Waist]                FLOAT (53)     NULL,
    [Hip]                  FLOAT (53)     NULL,
    [LifeStyle]            INT            NULL,
    [CusinePreference]     INT            NULL,
    [BloodGroup]           NVARCHAR (MAX) NULL,
    [Heamoglobin]          FLOAT (53)     NULL,
    [SystoleBP]            INT            NULL,
    [DiastoleBP]           INT            NULL,
    [HDL]                  FLOAT (53)     NULL,
    [TSH]                  FLOAT (53)     NULL,
    [RandomSugar]          FLOAT (53)     NULL,
    [FastingSugar]         FLOAT (53)     NULL,
    [PostPrandialSugar]    FLOAT (53)     NULL,
    [MedicalCondition]     NVARCHAR (MAX) NULL,
    [DailyCarbIntake]      FLOAT (53)     NULL,
    [DailyProteinIntake]   FLOAT (53)     NULL,
    [DailyFatIntake]       FLOAT (53)     NULL,
    [FitnessPlan]          INT            NULL,
    [Sex]                  INT            NULL,
    CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UC_username] UNIQUE NONCLUSTERED ([UserName] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [UserNameIndex]
    ON [dbo].[AspNetUsers]([UserName] ASC);

